# Generated by Django 3.1.2 on 2020-11-02 21:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0002_auto_20201102_1942'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='category',
            field=models.CharField(choices=[('HSG', 'Housing'), ('MDCL', 'Medical'), ('SVNG', 'Savings'), ('EMG', 'Emergency'), ('CTNG', 'Clothing'), ('ENT', 'Entertainment'), ('ULTS', 'Utilities'), ('EDCTN', 'Education'), ('MSC', 'Miscellaneous'), ('PSNL', 'Personal'), ('ISRNC', 'Insurance'), ('HSHIMS', 'Household items'), ('RTMNT', 'Retirement'), ('TNSPTN', 'Transportation'), ('FD', 'Food'), ('GFT', 'Gifts'), ('DBT', 'Debt')], default='MSC', max_length=255),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='money',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1000)]),
        ),
    ]
