# Generated by Django 3.1.2 on 2020-11-02 21:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0003_auto_20201102_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='category',
            field=models.CharField(choices=[('ENT', 'Entertainment'), ('CTNG', 'Clothing'), ('HSG', 'Housing'), ('EDCTN', 'Education'), ('HSHIMS', 'Household items'), ('TNSPTN', 'Transportation'), ('MDCL', 'Medical'), ('GFT', 'Gifts'), ('PSNL', 'Personal'), ('DBT', 'Debt'), ('MSC', 'Miscellaneous'), ('ULTS', 'Utilities'), ('RTMNT', 'Retirement'), ('SVNG', 'Savings'), ('EMG', 'Emergency'), ('ISRNC', 'Insurance'), ('FD', 'Food')], default='MSC', max_length=255),
        ),
        migrations.AlterField(
            model_name='envelope',
            name='money',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
