# Generated by Django 3.1.2 on 2020-11-03 21:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0004_auto_20201102_2148'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelope',
            name='category',
        ),
    ]
