# Generated by Django 3.1.3 on 2020-11-09 15:59

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0005_remove_envelope_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_amount', models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.ImageField(blank=True, null=True, upload_to='envelopes/')),
                ('merchant_name', models.CharField(max_length=255)),
                ('envelope', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipts', to='envelopes.envelope')),
            ],
        ),
    ]
