# Generated by Django 3.1.3 on 2020-11-13 19:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0006_receipt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='total_amount',
            field=models.FloatField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
