# Generated by Django 3.1.3 on 2020-11-13 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0007_auto_20201113_1933'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receipt',
            name='image',
        ),
    ]
