# Generated by Django 3.1.3 on 2020-11-16 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0008_remove_receipt_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='envelope',
            name='remaining',
            field=models.IntegerField(null=True),
        ),
    ]
