# Generated by Django 3.1.3 on 2020-11-16 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0009_envelope_remaining'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='envelope',
            name='remaining',
        ),
        migrations.AlterField(
            model_name='envelope',
            name='money',
            field=models.IntegerField(null=True),
        ),
    ]
