# Generated by Django 3.1.3 on 2020-11-16 17:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0010_auto_20201116_1735'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='money',
            field=models.IntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
