# Generated by Django 3.1.3 on 2020-11-16 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0011_auto_20201116_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='money',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
