# Generated by Django 3.1.3 on 2020-11-16 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0012_auto_20201116_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='money',
            field=models.IntegerField(null=True),
        ),
    ]
