# Generated by Django 3.1.3 on 2020-11-16 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('envelopes', '0013_auto_20201116_1738'),
    ]

    operations = [
        migrations.AlterField(
            model_name='envelope',
            name='money',
            field=models.FloatField(null=True),
        ),
    ]
